### ISSUE TITLE
Refreshing issue

### ISSUE THREAD

**Issue by Cam9731** [mykle1/MMM-WeatherOrNot#1]
For some reason, the module is not refreshing on the time set in config, it only refreshes on a PM2 restart of magicmirror or a system reboot

**Comment by mykle1** [comment]
You're right. A stupid omission on my part caused it to NOT refresh. My bad. I just fixed it and tested it for a few minutes. Do a `git pull` in the module directory to get the updated/fixed file. I hope you enjoy the module. Give me a shout on the forum! Peace!

**Comment by Cam9731** [comment]
Thanks so much! Easily the most adaptive and aesthetic weather module out there. Thanks for the quick fix too!

**Comment by mykle1** [comment]
I appreciate your kind words. I hope you enjoy the module as much as I enjoy making them.
