### ISSUE TITLE
Font size too small

### ISSUE THREAD

**Issue by monkeyboy126** [mykle1/MMM-WeatherOrNot#10]
Module works great but the text size is far too small for my screen.  How do I increase the font size?  Tried CSS and iFrame but I'm new to coding, so probably doing something wrong

**Comment by mykle1** [comment]
Unfortunately, you can't. The option to change the font size does not exist at the source. Only the options in the config are provided by the source. This module is inside an iFrame so you can't modify the text size as you normally would.

**Comment by chassain** [comment]
use 
transform: scale(2,2) in css iframe
