### ISSUE TITLE
Improvements : size of icons and writing

### ISSUE THREAD

**Issue by pgille** [mykle1/MMM-WeatherOrNot#12]
Hello !
First : thank you for your software
Could you please improve to make possible the management of the size of the icons and writings ?

It's too small on the screen !

Thank you
best regards

**Comment by BKeyport** [comment]
Font size is generated by the website. If adjusting the container size by height and width doesn't do it, there could be a way to request that feature from weatherwidget.io

**Comment by mykle1** [comment]
"Font size is generated by the website" says the Chief of the MM Investigation Unit.
