### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ghost** [mykle1/MMM-WeatherOrNot#13]
I have an update notification. 
How to update the module?

![image](https://user-images.githubusercontent.com/65309007/100336645-333aa700-2fb5-11eb-8091-2b6229476702.png)

**Comment by BKeyport** [comment]
From command prompt go to your MagicMirror Directory (likely ~/MagicMirror) 
then: 
cd modules/MMM-WeatherOrNot/
git pull 

then restart the mirror. 

This works for all modules, although some updates will also require the additional step of 
npm install 

-- Brendan

**Comment by 3v4ndr0** [comment]
thanks

**Comment by ghost** [comment]
Thanks

**Comment by mykle1** [comment]
Yo Brendan!

You can handle all my issues from now on.
