### ISSUE TITLE
CSS and JS

### ISSUE THREAD

**Issue by tomtomlsg72** [mykle1/MMM-WeatherOrNot#14]
Hello, can you change the size of the text and icons for a bigger display with css? 
How to add a capitalize so that the details under the icon is a capitalize?

Thank you

**Comment by mykle1** [comment]
Unfortunately, this module resides inside of an iframe so you won't be able to apply css to it, nor will you be able to modify the size of the text. Only the options in the config entry are available. Thanks for your interest. Peace!
