### ISSUE TITLE
Module not updating unless reload mirror

### ISSUE THREAD

**Issue by dsmig** [mykle1/MMM-WeatherOrNot#15]
Running into an issue on 2 separate mirrors where the WeatherOrNot module will not auto update unless the mirror is restarted/reloaded. 
All other modules are refreshing without issues. 

I do have this line in my code:

updateInterval: 10 * 60 * 1000,

I've checked to make sure the module is up to date. I don't see any errors within the developer tools console either.

**Comment by mykle1** [comment]
Odd. I just d/l a fresh install and it appears mine is updating as expected. In my config entry, I set my updateInterval to 20 * 1000. It successfully updated the module every 20 seconds. You should see the module fade out and fade back in the display. I then set the updateInterval back to 10*60*1000. Have you changed any of the module files? Have you tried a fresh install? Have you tried the module by itself to see if it updates? Are you saying the module doesn't change at all, even 24 hours later?

**Comment by dsmig** [comment]
Yea, I've tried fresh installs on both devices. So I can launch the mirror and all appears good but after a period of time during the day, it is still stuck on the temperature from when the mirror was launched. I can go several days without reloading it and it will still be on that same data from when it was first loaded. I don't see it fading any. I haven't modified any of the files outside of the below code. I'm not sure if this may have anything to do with it but when I do the uninstall/install, I have been using the third part module installer (mmpm - https://github.com/Bee-Mar/mmpm).


This is the entire code I have set in the config.js:

{
			disabled: false,
			module: 'MMM-WeatherOrNot',
			position: "top_bar",
			config: {
			location: "haslet",                // See instructions
			locationCode: "32d97n97d35",              // See instructions
			languages: "en",                          // See Languages list
			tempUnits: "F",                           // F or C
			font: "Noto Serif",                           // See Font list
			textColor: "#eeeeee",                     // Hex color codes.
			htColor: "#df0101",                       // high temp color. Hex color codes.
			ltColor: "#05e6fe",                       // low temp color. Hex color codes.
			sunColor: "#f8e502",                      // Hex color codes.
			moonColor: "#bfbdbd",                     // Hex color codes.
			cloudColor: "#dfdede",                    // Hex color codes.
			cloudFill: "#323232",                     // Hex color codes.
			rainColor: "#fcfcfd",                     // Hex color codes.
			snowColor: "#dfdede",                     // Hex color codes.
			height: "100%",                          // module is responsive to changes
			width: "100%",                          // module is responsive to changes
			days: "7",                                // 3, 5 or 7
			bgColor: "#000000",                       // theme overrides bgColor.
			icons: "Iconvault",              // Iconvault, Climacons or Climacons Animated
			animationSpeed: 3000,
			updateInterval: 10 * 60 * 1000,
				}
		},

**Comment by dsmig** [comment]
So interesting development, I re-cloned the module via command line and the same issue is happening. I changed the code refresh like you and it did not work. However, it was actually refreshing another module I have - MMM-MMM-RAIN-RADAR.  I removed the rain-radar coding from the config.js and reloaded the mirror and now your module was refreshing properly. I put the Rain Radar code back in, and it went back to not updating. Both modules have updateInterval call outs but something is conflicting. 

{
			disabled: false,
			module: 'MMM-WeatherOrNot',
			position: "top_bar",
			config: {
			location: "haslet",                // See instructions
			locationCode: "32d97n97d35",              // See instructions
			languages: "en",                          // See Languages list
			tempUnits: "F",                           // F or C
			font: "Noto Serif",                           // See Font list
			textColor: "#eeeeee",                     // Hex color codes.
			htColor: "#df0101",                       // high temp color. Hex color codes.
			ltColor: "#05e6fe",                       // low temp color. Hex color codes.
			sunColor: "#f8e502",                      // Hex color codes.
			moonColor: "#bfbdbd",                     // Hex color codes.
			cloudColor: "#dfdede",                    // Hex color codes.
			cloudFill: "#323232",                     // Hex color codes.
			rainColor: "#fcfcfd",                     // Hex color codes.
			snowColor: "#dfdede",                     // Hex color codes.
			height: "100%",                          // module is responsive to changes
			width: "100%",                          // module is responsive to changes
			days: "7",                                // 3, 5 or 7
			bgColor: "#000000",                       // theme overrides bgColor.
			icons: "Iconvault",              // Iconvault, Climacons or Climacons Animated
			animationSpeed: 3000,
			updateInterval: 20 * 1000
				}
		},

	{
    disabled: false,
    module: 'MMM-RAIN-RADAR',
    position: "upper_left",
    config: {
        useHeader: false, // true if you want a header
        lat: "32.92972875", // Latitude
        lon: "-97.37303829222954", // Longitude
        area: 'TX', // US State
        zoomLevel: 10,
        mapType: 3, //0-Road Map 1-Satellite 2-Dark Map 3-OpenStreetMaps 4-Light Map
        color: 3, //0-Original 1-Universal Blue 2-TITAN 3-The Weather Channel 5-NEXRAD Level-III 6-RAINBOW @ SELEX-SI
        snow: 1,
        smoothing: 1,
        opacity: 88,
        fastAnimation: 0,
        coverage: 0,
        darkTheme: 1,
        UTCtime: 0,
        legend: 0,
        legendMin: 0, //set legend to 1 if you want legendMin to show
        animate: 1,
        updateOnWarning: 1, // 1: after updateInterval, weather warnings for your US states will be used to determine if module should be hidden. 0 module is perpertually displayed
        updateInterval: 5 * 60 * 1000, // number of milliseconds. change 5 to 60 and it will update each 10 minutes
    }
},

**Comment by mykle1** [comment]
So, the module works but is in conflict with Rain Radar. An immediate thought would be to put the WeatherOrNot entry below the Rain Radar entry in the config. This may or may not resolve the issue but it is worth trying

**Comment by dsmig** [comment]
I made the adjustments as you mentioned and it appears it corrected the issue. Both modules are updating independently. Just out of curiosity, what would/did moving the code actually do? I wouldn't have thought module order would have been the factor. 

Thanks for the help. I will consider this closed.

**Comment by mykle1** [comment]
Basically, it changed the loading order of the modules. It doesn't always work, as I mentioned, but it does work in some circumstances. It's a whole lot easier to try that first than to try to track down where and what the conflict is. I'm glad it worked for you and I hope you enjoy the module.  Peace!

**Comment by hfrelat** [comment]
Hello.
I Just installe your module bud I had same issue
I tried to change the order but ko.
Have u tried something Else ?

Sorry for m'y englih and thanks for réponse.
