### ISSUE TITLE
Black square

### ISSUE THREAD

**Issue by almero69** [mykle1/MMM-WeatherOrNot#3]
Hi!
Do you know if this module will work with module called iFrame?
https://github.com/alberttwong/MMM-iFrame
If it works, how can I get it works together? Should I insert your module config into iFrame?
I'm newbie as you maybe understand :-)

**Comment by mykle1** [comment]
I'm not sure what you are asking. MMM-WeatherOrNot will work by itself. You don't need to use MMM-iFrame at all
