### ISSUE TITLE
Black Square

### ISSUE THREAD

**Issue by almero69** [mykle1/MMM-WeatherOrNot#4]
I ask you because the module only shows a black square. I think I have tried with everything but become black. Can you see in my config if I have done something wrong?

{
disabled: false,
module: "MMM-WeatherOrNot",
position: "top_right",
config: {
location: "Stockholm", // See instructions
locationCode: "59d3318d07", // See instructions
languages: "se", // See Languages list
tempUnits: "C", // F or C
font: "Tahoma", // See Font list
textColor: "#ffffff", // Hex color codes.
htColor: "#ffffff", // high temp color. Hex color codes.
ltColor: "#00dfff", // low temp color. Hex color codes.
sunColor: "#febc2f", // Hex color codes.
moonColor: "#dfdede", // Hex color codes.
cloudColor: "#dfdede", // Hex color codes.
cloudFill: "#1f567c", // Hex color codes.
rainColor: "#93bffe", // Hex color codes.
snowColor: "#dfdede", // Hex color codes.
height: "100%", // module is responsive to changes
width: "100%", // module is responsive to changes
label: "New Dorp", // Location seems logical . .
label2: "Staten Island", // . . . or anything you like
days: "3", // 3, 5 or 7
theme: "Dark", // See Themes list *** theme overrides bgColor. ***
bgColor: "#000000", // theme overrides bgColor.
icons: "Climacons Animated", // Iconvault, Climacons or Climacons Animated
animationSpeed: 3000,
updateInterval: 10 * 60 * 1000,
}
},

**Comment by mykle1** [comment]
location: "stockholm", // NO CAPITAL S
languages: "sv", // for Swedish
