### ISSUE TITLE
Odd code after weather 1587347317471

### ISSUE THREAD

**Issue by Syngather** [mykle1/MMM-WeatherOrNot#5]
I changed the background of the whole mirror, when I did I found this number under the WeatherOrNot, if I remove the module it goes away, however i can not find where in your module it is coming from or how to remove it.

![image](https://user-images.githubusercontent.com/63986458/79707056-147e7000-8270-11ea-82a8-a09a7baf9568.png)

**Comment by mykle1** [comment]
You can't target that number to remove it because this module is inside an iFrame. It likely has something to do with your changing the background of the whole mirror. I am unable to reproduce that on  my end

**Comment by Syngather** [comment]
Is there a way to change the background of just your app, which would then hide it? or are you saying your app only works on a black background?

**Comment by mykle1** [comment]
If you look at the config options you will see "bgColor: "#000000", // theme overrides bgColor." Be guided by that.
