### ISSUE TITLE
Unable to use themes

### ISSUE THREAD

**Issue by lbyerley** [mykle1/MMM-WeatherOrNot#6]
@mykle1 
Hi and thank you for your work on this module.

Please excuse my noobness but I can't seem to get any of the themes to work.  I've copied my entry from config.js below. Changing any of the themes results in the same affect. Is there meant to be a themes folder or where are the themes referenced. Everything else works perfectly.

Thank you for your time

                        disabled: false,
                        module: "MMM-WeatherOrNot",
                        position: "top_right",
                        config: {
                        location: "midrand",                      // See instructions
                        locationCode: "n27b0034t12",              // See instructions
                        languages: "en",                          // See Languages list
                        tempUnits: "C",                           // F or C
                        font: "Roboto",                           // See Font list
                        textColor: "#ffffff",                     // Hex color codes.
                        htColor: "#ffffff",                       // high temp color. Hex color codes.
                        ltColor: "#00dfff",                       // low temp color. Hex color codes.
                        sunColor: "#febc2f",                      // Hex color codes.
                        moonColor: "#dfdede",                     // Hex color codes.
                        cloudColor: "#dfdede",                    // Hex color codes.
                        cloudFill: "#1f567c",                     // Hex color codes.
                        rainColor: "#93bffe",                     // Hex color codes.
                        snowColor: "#dfdede",                     // Hex color codes.
                        height: "560px",                          // module is responsive to changes
                        width: "180px",                           // module is responsive to changes
                        label: "Midrand",                         // Location seems logical . .
                        label2: "Casa Monterosso",                // . . . or anything you like
                        days: "7",                                // 3, 5 or 7
                        theme: "dark",                            // See Themes list *** theme overrides bgColor. ***
                        bgColor: "#000000",                       // theme overrides bgColor.
                        icons: "Climacons Animated",              // Iconvault, Climacons or Climacons Animated
                        animationSpeed: 3000,

**Comment by mykle1** [comment]
Yes, there is a problem. Some of the themes work and some of them don't. I'll take a look at whats going on and see if there is anything I can do about it. For the time being, you'll have try them all and see which DO work. Please use all lower case in the config. Ex theme: "ruby" or theme: "tile_wood" or theme: "random_grey". Those 3 are working. Please try again

**Comment by lbyerley** [comment]
Thank you for your reply. I'll go with one of those for now.

Many thanks.

**Comment by mykle1** [comment]
Ok, but I didn't try them all. You can go through them if you like. I'm feeling a bit lazy today. haha

**Comment by lbyerley** [comment]
:P Fair enough. Thanks for the help.
