### ISSUE TITLE
Random numbers at the bottom of the module

### ISSUE THREAD

**Issue by usafle** [mykle1/MMM-WeatherOrNot#8]
I have strange random numbers at the bottom of the module - no idea where they are populating from and no idea how to get rid of them

[Screenshot](https://ibb.co/02555x9)

**Comment by mykle1** [comment]
Post your config entry for this module in the forum. I'm not seeing this behavior and you are the first to report it.

**Comment by usafle** [comment]
Which forum?  I've only used Github for 3rd party MM modules....

**Comment by MikeBishop** [comment]
I'm seeing this as well.  It appears to be the change in 25f65d35c803f; the timestamp is getting displayed as part of the body of the iframe.  I've worked around this by forcing the height so the number gets cut off, but it's definitely a bug.

**Comment by MikeBishop** [comment]
![image](https://user-images.githubusercontent.com/4273797/91734992-acbf2680-eb79-11ea-8b03-26dee356805f.png)

I presume your intention was to have this in the URL, not in the body of the page.

**Comment by usafle** [comment]
> 
> 
> I'm seeing this as well. It appears to be the change in [25f65d3](https://github.com/mykle1/MMM-WeatherOrNot/commit/25f65d35c803f70bf796c2b20d4d648c6bff3c02); the timestamp is getting displayed as part of the body of the iframe. I've worked around this by forcing the height so the number gets cut off, but it's definitely a bug.

I've changed the height (and width) in the config.js file multiple times and still these numbers show up.  I'm assuming you have changed the height somewhere else then?

Also, thanks for investigating this issue and bringing it up again.   

I was pretty much _dismissed_ 21 days ago.

**Comment by MikeBishop** [comment]
I added this to custom.css:

    iframe.iframe {
      width: 100%;
      max-height: 100px;
    }

**Comment by usafle** [comment]
Well hopefully @mykle1 takes notice of the issue and fixes this now.
