### ISSUE TITLE
5 Days

### ISSUE THREAD

**Issue by aareben** [mykle1/MMM-WeatherOrNot#9]
I probably messed something up in setting up but it will only show 5 days when I wrote in 7. If anyone could help that would be great. This is my config.

{
    			disabled: false,
    			module: 'MMM-WeatherOrNot',
    			position: 'top_right',
    			config: {
      				location: "new-york",                // See instructions
      				locationCode: "40d71n74d01",              // See instructions
      				languages: "en",                          // See Languages list
      				tempUnits: "F",                           // F or C
      				font: "Roboto",                           // See Font list
      				textColor: "#ffffff",                     // Hex color codes.
      				htColor: "#ffffff",                       // high temp color. Hex color codes.
      				ltColor: "#ffffff",                       // low temp color. Hex color codes.
      				sunColor: "#febc2f",                      // Hex color codes.
      				moonColor: "#dfdede",                     // Hex color codes.
      				cloudColor: "#dfdede",                    // Hex color codes.
      				cloudFill: "#1f567c",                     // Hex color codes.
      				rainColor: "#93bffe",                     // Hex color codes.
      				snowColor: "#dfdede",                     // Hex color codes.
      				height: "700px",                          // module is responsive to changes
      				width: "350px",                          // module is responsive to changes
      				label: "NYC",                        // Location seems logical . .
      				label2: "Home",                  // . . . or anything you like
      				days: "7",                                // 3, 5 or 7
      				theme: "dark",                            // See Themes list *** theme overrides bgColor. ***
      				bgColor: "#000000",                       // theme overrides bgColor.
      				icons: "Climacons",              // Iconvault, Climacons or Climacons Animated
      				animationSpeed: 3000,
      				updateInterval: 10 * 60 * 1000,
    				}
		},

**Comment by aareben** [comment]
I realize i probably have the size ratio wrong. What would be best?

**Comment by mykle1** [comment]
You have to try different widths and heights till you see what you like. I have it in the bottom bar, width 1080px and I see 7 days
